CREATE TABLE `enuminfo` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(500) NULL DEFAULT NULL,
	`value` VARCHAR(500) NULL DEFAULT NULL,
	`type` VARCHAR(500) NULL DEFAULT NULL,
	`comment` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE
)